language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

script:
  - julia -e 'using Pkg;
              Pkg.activate(".");
              Pkg.add("Conda");
              using Conda;
              Conda.add("sympy");
              ENV["PYTHON"] = "";
              Pkg.build("PyCall");'
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("MomentExpansions")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())';